# Generated by Django 5.0.3 on 2024-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_genre_name_alter_movie_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="movies",
            field=models.ManyToManyField(related_name="genres_set", to="movies.movie"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                related_name="movies_set_in_movies", to="movies.genre"
            ),
        ),
    ]
